name: Integration Tests
on:
  pull_request:
    branches:
      - master

jobs:
  integration-test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        test-name: [
          'boostPayment', 'botCreation', 'chatPayment', 'cleanup', 'clearAllChats',
          'clearAllContacts', 'contacts', 'images', 'latestTest', 'lsats', 'paidMeet',
          'paidTribeImages', 'queryRoutes', 'self', 'sphinxPeople', 'streamPayment',
          'tribe', 'tribe3Escrow', 'tribe3Messages', 'tribe3Private', 'tribe3Profile',
          'tribeEdit', 'tribeImages', 'messageLength', 'transportToken', 'pinnedMsg',
          'hmac', 'socketIO', 'ampMessage'
        ]
    steps:
    - name: Enable docker.host.internal for Ubuntu
      run: |
        pwd && sudo bash -c 'echo "172.17.0.1 host.docker.internal" >> /etc/hosts'
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: relay
    - name: Build Relay
      working-directory: ./relay
      run: |
        npm install && npm run build && docker build -t sphinxlightning/sphinx-relay .
    - name: Checkout stack
      run: |
        git clone -b amp https://github.com/antonilol/sphinx-stack.git stack
    - name: give permissions
      working-directory: ./stack
      run: |
        chmod 777 ./bitcoind;
        chmod 777 ./relay;
    - name: Turn on Stack
      working-directory: ./stack
      run: |
        GITACTION_ENV=gitactionenv docker-compose up -d
    - name: wait for setup to finish
      working-directory: ./stack
      run: |
         docker logs -f stack_relaysetup_1
         docker logs -f stack_lndsetup_1
         sleep 2m
    - name: copy nodes.json
      run: |
        mkdir relay/src/tests/configs
        cp stack/relay/NODES.json relay/src/tests/configs/nodes.json
    - name: Run tests
      working-directory: ./relay
      run: .github/workflows/test.sh ${{matrix.test-name}}
