name: Lint and build
on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on:
      - ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install npm dependencies
        run: npm i
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}  
      - name: lint and push automatic fixes
        run: |
          npm run lint || echo -n
          git config user.name 'Github Actions'
          git config user.email github-actions@github.com
          git add src
          git commit -m "Automatic linter fixes" || echo -n
          npm run build || echo -n
          git add dist
          git commit -m "Automatic build" || echo -n
          git push
