name: Lint (Pull Request)
on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint (Pull Request)
    runs-on:
      - ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install npm dependencies
        run: npm i
      - name: lint
        run: npm run lint
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
